services:
  web:
    container_name: web_app_container
    env_file:
      - ../.env
    environment:
      - FLASK_ENV=development
      - ZENODO_API_URL=http://fakenodo:5000/api/deposit/depositions
      - ZENODO_ACCESS_TOKEN=fake_token
    expose:
      - "5000"
    depends_on:
      - db
      - selenium-hub
      - mailpit 
      - fakenodo
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.dev
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "sh", "-c", "sh /app/docker/entrypoints/development_entrypoint.sh" ]
    networks:
      - uvlhub_network

  db:
    container_name: mariadb_container
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uvlhub_network


  mailpit:
    image: axllent/mailpit
    container_name: mailpit_catcher_container
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - uvlhub_network
  
  nginx:
    container_name: nginx_web_server_container
    image: nginx:1.29.1
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - uvlhub_network

  selenium-hub:
    container_name: selenium_hub_container
    image: selenium/hub:latest
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - uvlhub_network

  selenium-chrome:
    container_name: selenium_chrome_container
    image: selenium/node-chrome:latest
    shm_size: 2gb
    ports:
      - "5900:5900"
    env_file:
      - ../.env.selenium
    depends_on:
      - selenium-hub
    networks:
      - uvlhub_network

  selenium-firefox:
    container_name: selenium_firefox_container
    image: selenium/node-firefox:latest
    shm_size: 2gb
    ports:
      - "5901:5900"
    env_file:
      - ../.env.selenium
    depends_on:
      - selenium-hub
    networks:
      - uvlhub_network
  fakenodo:
    build: ../fakenodo 
    container_name: fakenodo
    ports:
      - "5000:5000"
    networks:
      - uvlhub_network
  
  locust:
    image: locustio/locust
    container_name: locust_container
    ports:
      - "8089:8089"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "../:/mnt/locust"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - uvlhub_network
    user: root
    entrypoint: []
    command: >
      sh -c "ln -sfn /mnt/locust /app && apt-get update && apt-get install -y g++ build-essential && pip install -r /app/requirements.txt && cd /app && locust"

volumes:
  db_data:

networks:
  uvlhub_network: